config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'cats#index'
  # Defines the root path route ("/")
  # root "articles#index"
  resources :cats, except: [:destroy] do
    resources :cat_rental_requests, only: [:new]
  end
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post 'approve'
      post 'deny'
    end
  end
  delete "/sessions.:session_id", to: "sessions#destroy_remote"
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  
end

app/models/user.rb
class User < ApplicationRecord
    validates :user_name, presence: true, uniqueness: true
    validates :password_digest, presence: { message: 'Password can\'t be blank' }
    validates :session_token, presence: true, uniqueness: true
    validates :password, length: { minimum: 6, allow_nil: true }

    after_initialize :ensure_session_token

    has_many :cats,
        primary_key: :id,
        foreign_key: :user_id,
        class_name: :Cat

    has_many :rental_requests,
        primary_key: :id,
        foreign_key: :user_id,
        class_name: :CatRentalRequest

    has_many :sessions,
        primary_key: :id,
        foreign_key: :user_id,
        class_name: :Session

    attr_reader :password

    def self.find_by_credentials(user_name, password)
        user = User.find_by(user_name: user_name)
        return nil unless user
        user.is_password?(password) ? user : nil
    end

    def generate_session_token
        session_token = SecureRandom.urlsafe_base64
    end
    def self.generate_session_token
        self.save!
        self.session_token
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    private

    def ensure_session_token
        self.session_token ||= self.generate_session_token
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in?, only: [:new, :create]
    before_action :logged?, only: [:show]
    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login!(@user)
            redirect_to cats_url
        else
            flash[:alert] = @user.errors.full_messages.join(", ")
            redirect_to new_user_url
        end
          
    end
    def show
        @sessions = Session.where(user_id: current_user.id)
        render :show
    end
    private
    def user_params
        params.require(:user).permit(:user_name, :password)
    end
end

app/views/users/_user.html.erb
<main>
    <section class="page">
        <div class="centered-box"> 
            <%= form_for @user do |f| %>
            <h1><%= usertitle %></h1>
            <label for="user_name">User Name</label>
            <%= f.text_field :user_name%>
            <br>
            <label for="password">Password</label>
            <%= f.password_field :password%>
            <br>
            <%= f.submit "Enviar" %>
            <%end%>
        </div>
    </section>
</main>

app/views/users/new.html.erb
<% usertitle = "New User"%>

<%= render "user", usertitle: usertitle%>

app/views/users/show.html.erb
<main>
    <section class="page">
        <div class="centered-box"> 
            <h1><%=current_user.user_name%></h1>
            <table>
                    <thead>
                        <tr>
                            <th>Device</th>
                            <th>Location</th>
                            <th>Session</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @sessions.each do |sessions|%>
                            <tr>
                                <td><%=sessions.device%></td>
                                <td><%=@location%></td>
                                <td><%= button_to "Terminate Session", sessions_path(sessions.id), method: :delete %></td>
                            </tr>
                        <% end %>
                    </tbody>
            </table>
        </div>
    </section>
</main>