config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'cats#index'
  # Defines the root path route ("/")
  # root "articles#index"
  resources :cats, except: [:destroy] do
    resources :cat_rental_requests, only: [:new]
  end
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post 'approve'
      post 'deny'
    end
  end
  delete "/sessions.:session_id", to: "sessions#destroy_remote"
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  
end

app/models/cat.rb
require 'action_view'
class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper
    CAT_COLOR = %w[black white orange grey].freeze
    
    validates :color, inclusion: { in: CAT_COLOR, message: "%{value} is not a valid color" }, presence: true
    validates :sex, inclusion: { in: %w(M F), message: "%{value} is not a valid sex"}, presence: true
    validates :birth_date, presence: true
    validates :name, presence: true
    validates :description, presence: true
    validate :birth_date_cannot_be_future

    has_many :rental_requests,
        primary_key: :id,
        foreign_key: :cat_id,
        class_name: :CatRentalRequest,
        dependent: :destroy

    belongs_to :owner,
        class_name: "User",
        foreign_key: :user_id,
        primary_key: :id,
        required: true

    def birth_date_cannot_be_future
        return unless birth_date.present? && birth_date > Date.today
        errors.add(:birth_date, "can't be in the future")
    end

    def age
        time_ago_in_words(birth_date)
    end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
    before_action :logged?, only: [:edit, :update, :new, :create]
    before_action :set_current_user, only: [:edit, :update]
    before_action :check_owner, only: [:edit, :update]
    
    def index
        @cats = Cat.all
        render :index
    end

    def show
        @cat = Cat.includes(rental_requests: :requester).find(params[:id])
        render :show
    end

    def new
        @cat = Cat.new
        render :new
    end

    def create
        @cat = Cat.new(cat_params)
        @cat.user_id = current_user.id
        if @cat.save
            redirect_to cat_url(@cat)
        else
            render :new
        end
    end

    def edit
        @cat = current_user.cats.find(params[:id])
        render :edit
    end

    def update
        @cat = current_user.cats.find(params[:id])
        if @cat.update(cat_params)
            redirect_to cat_url(@cat)
        else
            render :edit
        end
    end

    private
    def cat_params
        params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
    end

end

app/views/cats/_form.html.erb
<main>
  <section class="page">
    <div class="centered-box">
      <%= form_for @cat do |f| %>
        <h1><%= mytitle %></h1>
          <label for="name">Name</label>
          <%= f.text_field :name%>
          <br>
          <label for="birth_date">Birth Date</label>
          <%= f.date_field :birth_date%>
          <br>
          <label for="color">Color</label>
          <select id="color" name="cat[color]">
              <option disable selected>-- Please Select --</option>
              <% Cat::CAT_COLOR.each do |color|%>
                <option
                  <%= @cat.color == color ? "selected" : "" %>
                  value="<%= color %>">
                  <%= color.upcase %>
                </option>
              <% end %>
          </select>
          <br>
          <label for="sex">Sex</label>
          <%= f.radio_button :sex, 'M'%>M
          <%= f.radio_button :sex, 'F'%>F
          <br>
          <label for="description">Description</label>
          <%= f.text_area :description%>
          <br>
          <%= f.submit @cat.new_record??
          "Add a cat" : "Update a cat" %>
      <%end%>
    </div>
  </section>
</main>

app/views/cats/_rep.html.erb
<tr>
  <td><%= req.requester ? req.requester.user_name : "No data"%></td>
  <td><%= req.start_date %></td>
  <td><%= req.end_date %></td>
  <td>
    <% if req.pending? && current_user && current_user.cats.include?(req.cat) %>
      <form action="<%= approve_cat_rental_request_url(req) %>" method="post">
        <input type="submit" value="Approve">
      </form>
      <form action="<%= deny_cat_rental_request_url(req) %>" method="post">
        <input type="submit" value="Deny">
      </form>
    <% else %>
      <%= req.status %>
    <% end %>
  </td>
</tr>

app/views/cats/edit.html.erb
<% mytitle = 'Edit a cat!'%>

<%= render 'form', mytitle: mytitle%>

app/views/cats/index.html.erb
<main>
  <section class="cat-index-holder">
     <nav><h1>My Cats</h1>
     <a href="<%= new_cat_url %>"><input class="button1" type ="button" value ="Add a cat" ></a>
     </nav> 
   <section class="cat-index">
    <% @cats.each do |cat| %>
      <div class="cat-index-item">
        <div>
          <img src="https://placekitten.com/g/231/231">
          <br>
          <a href="<%= cat_url(cat) %>"><%= cat.name %></a>
        </div>
      </div>
    <% end %>
  </section>
  </section>
</main>

app/views/cats/new.html.erb
<% mytitle = 'Create a cat!'%>

<%= render 'form', mytitle: mytitle %>

app/views/cats/show.html.erb
<main>
    <section class="page">
        <div class="centered-box">
            <img src="https://placekitten.com/g/231/231">
            <h1><%= @cat.name %></h1>
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Age</th>
                        <th>Color</th>
                        <th>Sex</th>
                        <th>Descriptcion</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><%= @cat.name %></td>
                        <td><%= @cat.age %></td>
                        <td><%= @cat.color %></td>
                        <td><%= @cat.sex %></td>
                        <td><%= @cat.description %></td>
                    </tr>
                </tbody>
            </table>
            <br>
            <a href="<%= edit_cat_url %>"><input class="button2" type ="button" value ="Edit cat" ></a>

            <br><br>
            <h1>Rental Requests</h1>
            <% if @cat.rental_requests.empty? %>
                <p>No rental requests for this cat</p>
            <% else %>
                <table>
                    <thead>
                        <tr>
                            <th>Requester</th>
                            <th>Start Date</th>
                            <th>End Date</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @cat.rental_requests.each do |req| %>
                            <%= render 'rep', req: req %>
                        <% end %>
                    </tbody>
                </table>
            <% end %>
            <a href="<%= new_cat_cat_rental_request_url(@cat) %>">
                Create a rental request
            </a>
        </div>
    </section>
</main>